name: Feature request
description: Suggest an improvement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What are you trying to do?
      description: The use case, not the solution. It helps us find the right design.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed change
  - type: checkboxes
    id: contribute
    attributes:
      label: Contributing
      options:
        - label: I'd like to implement this myself
