[book]
title = "tickrail developer guide"
authors = ["The tickrail Authors"]
language = "en"
src = "src"

[output.html]
git-repository-url = "https://github.com/upendrx/tickrail"
edit-url-template = "https://github.com/upendrx/tickrail/edit/main/docs/{path}"
